version: '3.1'
services:
  db:
    # image: postgres
    # restart: always
    # volumes:
    #   - /var/lib/postgresql/data:/var/lib/postgresql/data
    # environment:
    #   # POSTGRES_PASSWORD: postgres
    #   # POSTGRES_USER: postgres
    #   # POSTGRES_DB: postgres
  back:
    image: noshimorimoshi/my-koa-app
    ports:
      - 80:3000
    deploy:
      restart_policy:
        condition: on-failure
    placement:
        constraints:
          - node.labels.ip == global
  front:
  pbx:
    # ```sh
    #     apk add asterisk dahdi-linux libpri
    #     cd /etc/asterisk
    #     apk add asterisk-sample-config
    # ```
    # ```sh
    #     mv extensions.conf extensions.sample
    #     nano extensions.conf
    #     # [from-internal]
    #     # exten = 100,1,Answer()
    #     # same = n,Wait(1)
    #     # same = n,Playback(hello-world)
    #     # same = n,Hangup()
    # ```
    # ```sh
    #     nano sip.conf
    #     #[general]
    #     #context=default
    #     #
    #     #[6001]
    #     #type=friend
    #     #context=from-internal
    #     #host=dynamic
    #     #secret=unsecurepassword
    #     #disallow=all
    #     #allow=ulaw
    # ```
    # ```sh
    #     nano pjsip.conf
    #     # [transport-udp]
    #     # type=transport
    #     # protocol=udp
    #     # bind=0.0.0.0
    #     # 
    #     # [6001]
    #     # type=endpoint
    #     # context=from-internal
    #     # disallow=all
    #     # allow=ulaw
    #     # auth=6001
    #     # aors=6001
    #     # 
    #     # [6001]
    #     # type=auth
    #     # auth_type=userpass
    #     # password=unsecurepassword
    #     # username=6001
    #     # 
    #     # [6001]
    #     # type=aor
    #     # max_contacts=1
    # ```
volumes:
